# /**:
#     ros__parameters:
        # log_level: 0 # 0 = log nothing?






############  Global parameters  #############

/*/heartbeat_node:
    ros__parameters:
        heartbeat_publish_rate: 20.0

/*/batman_monitor:
    ros__parameters:
        network_information_publish_rate: 1.0
        batman_interface_name: bat0

/*/wifi_monitor:
    ros__parameters:
        network_information_publish_rate: 1.0
        mesh_interface_name: mesh0

/*/video_streaming_node:
    ros__parameters:
        # topic: /camera/camera/color/image_raw
        topic: /camera/camera/color/image_raw # TODO: add annotated camera topic here!
        # topic: /camera/camera/color/image_raw # TODO: add annotated camera topic here!
        out_width: 480
        out_height: 360
        out_fps: 10
        receiver: "172.30.30.100"
        port: 5000
        bitrate_kbps: 400
        srt_latency_ms: 200
        record_mode: "none"
        # segment_time: 60
        # segment_pattern: "realsense-%Y%m%d-%H%M%S.ts"

# /*/video_receiver_node:
#     ros__parameters:
#         out_width: 480
#         out_height: 360
#         ip: "172.30.30.10"
#         port: 5000
#         out_topic: "received_video/image_raw"
#         srt_latency_ms: 200



############  Auction_server parameters  #############



/auction_server/auction_server_node:
    ros__parameters:
        auction_round_time: 1.0
        num_bids_end_auction: 3
        tasks_allocated_per_agent: 1


############  ######  #############










# TEST

/test/test_behavior_tree:
    ros__parameters:
        px4_namespace: "/px4_2"
        at_point_tolerance_radius: 1.25


/test/px4_controller:
    ros__parameters:
        px4_namespace: "/px4_2"


###









############  panda0  #############

# /panda0/test_behavior_tree:
#     ros__parameters:
#         px4_namespace: ""
#         at_point_tolerance_radius: 1.25
#         flying_height: 10

/panda0/px4_controller:
    ros__parameters:
        px4_namespace: ""
        agent_id: 0

/panda0/heartbeat_node:
    ros__parameters:
        px4_namespace: ""
        agent_name: "panda0"
        agent_id: 0

/panda0/auction_client:
    ros__parameters:
        client_name: "panda0"
        client_id: 0

/panda0/cost_calculator:
    ros__parameters:
        can_do_line_task: True
        can_do_point_task: True

/panda0/task_client:
    ros__parameters:
        px4_namespace: ""
        use_groot: true
        groot_port: 5557

/panda0/px4_controller:
    ros__parameters:
        px4_namespace: ""
        agent_id: 0



############  ######  #############








############  panda1  #############

# /panda1/test_behavior_tree:
#     ros__parameters:
#         px4_namespace: ""
#         at_point_tolerance_radius: 1.25
#         flying_height: 12

/panda1/px4_controller:
    ros__parameters:
        px4_namespace: ""
        agent_id: "1"

/panda1/heartbeat_node:
    ros__parameters:
        px4_namespace: ""
        agent_name: "panda1"
        agent_id: 1

/panda1/auction_client:
    ros__parameters:
        client_name: "panda1"
        client_id: 1

/panda1/cost_calculator:
    ros__parameters:
        can_do_line_task: False
        can_do_point_task: True


/panda1/task_client:
    ros__parameters:
        px4_namespace: ""
        use_groot: false
        groot_port: 5557

/panda1/px4_controller:
    ros__parameters:
        px4_namespace: ""
        agent_id: 1

############  ######  #############








############  nuc1  #############

# /nuc1/test_behavior_tree:
#     ros__parameters:
#         px4_namespace: ""
#         at_point_tolerance_radius: 1.25
#         flying_height: 12

/nuc1/px4_controller:
    ros__parameters:
        px4_namespace: ""
        agent_id: "1"

/nuc1/heartbeat_node:
    ros__parameters:
        px4_namespace: ""
        agent_name: "nuc1"
        agent_id: 1

/nuc1/auction_client:
    ros__parameters:
        client_name: "nuc1"
        client_id: 1

/nuc1/cost_calculator:
    ros__parameters:
        can_do_line_task: False
        can_do_point_task: True


/nuc1/task_client:
    ros__parameters:
        px4_namespace: ""
        use_groot: false
        groot_port: 5557

/nuc1/px4_controller:
    ros__parameters:
        px4_namespace: ""
        agent_id: 1

############  ######  #############










